AWSTemplateFormatVersion: '2010-09-09'
Description: container on ecs cluster

Resources:

  TaskDef:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: project-n-backend
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !ImportValue ECSTaskExecutionRole
      ContainerDefinitions:
        - Name: backend-python-server
          Image: 433481609008.dkr.ecr.us-east-1.amazonaws.com/project-n/backend-python-server:latest
          PortMappings:
            - ContainerPort: 8000
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: 'project-n'
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: 'backend-python-server'
        - Name: backend-web-server
          Image: 433481609008.dkr.ecr.us-east-1.amazonaws.com/project-n/backend-web-server:latest
          PortMappings:
          - ContainerPort: 80
            Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
                awslogs-group: 'project-n'
                awslogs-region: !Ref AWS::Region
                awslogs-stream-prefix: 'backend-web-server'

  Service:
    Type: AWS::ECS::Service
    DependsOn: ListenerRule
    Properties:
      ServiceName: backend-service
      TaskDefinition: !Ref TaskDef
      Cluster: !ImportValue project-n-cluster
      LaunchType: FARGATE
      DesiredCount: 2
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 70
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !ImportValue project-n-Subnet1
            - !ImportValue project-n-Subnet2
          SecurityGroups:
            - !ImportValue project-n-backend-security-group
      LoadBalancers:
        - ContainerName: backend-web-server
          ContainerPort: 80
          TargetGroupArn: !Ref TargetGroup

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: backend-tg
      VpcId: !ImportValue project-n-VPC
      Port: 80
      Protocol: HTTP
      Matcher:
        HttpCode: 200-299
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /health_check/
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 10
      TargetType: ip

  ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !ImportValue project-n-backend-listener
      Priority: 2
      Conditions:
        - Field: path-pattern
          Values:
            - /*
      Actions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward


Outputs:

  ApiEndpoint:
    Description: project-n API Endpoint
    Value: !Join ['', ['http://', !ImportValue project-n-api]]
    Export:
      Name: 'ProjectNApiEndpoint'