AWSTemplateFormatVersion: "2010-09-09"
Description: Postgres RDS Setup

Resources:

  Database:
    Type: AWS::RDS::DBInstance
    Properties:
      DBSubnetGroupName: !Ref DbSubnetGroup
      Engine: postgres
      DBName: project_n_prod
      MasterUsername: pn6447396393843
      MasterUserPassword: zzPgofrexkqpM2HTu6Gs6Bx98jXMdCNz
      DBInstanceClass: db.t2.micro
      AllocatedStorage: 5
      VPCSecurityGroups:
      - !Ref SecurityGroup

  DbSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties: 
      DBSubnetGroupDescription: project-n Subnet Group
      SubnetIds: 
        - !ImportValue project-n-Subnet1
        - !ImportValue project-n-Subnet2

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for RDS Database
      VpcId: !ImportValue 'project-n-VPC'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 0.0.0.0/0

  # DBSecurityGroup:
  #   Type: AWS::RDS::DBSecurityGroup
  #   Properties:
  #     EC2VpcId: !ImportValue 'project-n-VPC'
  #     GroupDescription : Database security group
  #     DBSecurityGroupIngress:
  #       - IpProtocol: tcp
  #         FromPort: 5432
  #         ToPort: 5432

# Outputs:

#   RdsDbId:
#     Description: "RDS Database ID"
#     Value: !Ref "Database"

#   DbName:
#     Description: "RDS Database Name"
#     Value: !Ref "DBName"

#   RdsDbURL:
#     Description: "RDS Database URL"
#     Value: !GetAtt "Database.Endpoint.Address"

#   DbUser:
#     Description: "RDS Database admin account user"
#     Value: !Ref "MasterUsername"

#   DbPassword:
#     Description: "RDS Database admin account password"
#     Value: !Ref "MasterUserPassword"
